swagger: "2.0"
info:
  title: Rating Control Service
  description: Contract file for Rating Control Service
  version: 1.0.0
  contact:
    name: Tolga TUNA
    url: http://duriancodes.com
    email: tolga.tuna@hotmail.com
  termsOfService: Rating Control Service indicate eligibility about book read suitable based on control level set
  license:
    name: api-test.com
    url: 'http://api-test.com'
schemes:
  - https
host: $(catalog.host)
basePath: /rating-control
produces:
  - application/json
paths:
  '/rcl/book/v1/read/eligibility/{control_level}/{book_id}':
    get:
      responses:
        200:
          description: OK
          schema:
            type: boolean
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - rcl
      summary: get Control Access
      operationId: getControlAccess
      description: Indicates if customer can read the requested book or not based on rating control level set
      parameters:
        - name: control_level
          type: string
          required: true
          in: path
          description: set control level
        - name: book_id
          type: string
          required: true
          in: path
          description: book id of desired book
definitions:
  ErrorResponse:
    properties:
      code:
        type: string
        description: error code
      message:
        type: string
        description: error message
    additionalProperties: false
    required:
      - code
      - message
tags: []
